#pragma once

#include "scop40bench.h"
#include "fastbench.h"
#include "flat_profiles.h"
#include "flat_aligner.h"
#include "flat_features.h"

class flat_bench : public FastBench
	{
public:
// Hard-coded score-like not Evalue-like
//	SBSCORE m_SBS = SBS_Evalue;

	float m_Open = -999;
	float m_Ext = -999;
	uint m_ThreadCount = 0;

////////////////////////////////
// Hits generated by this search
////////////////////////////////
	atomic<uint> m_NextQueryIdx = 0;
	atomic<uint> m_NextDopeIdx = 0;
	float *m_Scores = 0;
	uint *m_ScoreOrder = 0;

//////////////////////////////
// Flat profiles
// May be superset of lookup
//////////////////////////////
	flat_profiles m_fp;
	flat_features m_ff;

public:
	static atomic<uint> m_progress_counter;
	static atomic<uint> m_ncachehits;
	static atomic<uint> m_ncachemisses;

public:
	uint get_nfeat() const { return m_ff.get_nfeat(); }
	void ThreadBody_All(uint ThreadIdx);
	void ThreadBody_Dope(uint ThreadIdx);
	void Search(const string &how);
	void ApplyWeightsToLogOdds(const unordered_map<string, float> &Weights);
	void SetScalarParams(
		const vector<string> &Names,
		const vector<float> &Values);
	void UpdateParamsFromVarStr(const string &VarStr);
	void load_alphas_and_profiles(
		const vector<string> &feature_names,
		const vector<float> &weights,
		const string &fafnpattern,
		const string &logoddsfnpattern);
	void ProgressLogParams() const;
	void align_pair(const string &labelQ, const string &labelT);

public:
	static void ClassifyParams(
		const vector<string> &Names,
		const vector<float> &Values,
		vector<string> &AlphaNames,
		vector<float> &Weights,
		vector<string> &ScalarNames,
		vector<float> &ScalarValues);
	static void StaticThreadBody(flat_bench *SB,
		uint ThreadIdx, const string &how);;
	};

void ParseVarStr(
	const string &VarStr,
	vector<string> &Names,
	vector<float> &Weights);

void TruncLabel(string &Label);
