#pragma once

#include "scop40bench.h"
#include "fastbench.h"

typedef float (*ALIGN_FN)();

class flat_subsetbench
	{
public:
	SBSCORE m_SBS = SBS_Evalue;

///////////////////////////////////
// Lookup
// Defines label->domidx mapping
// See validate_mappings()
///////////////////////////////////
	vector<string> m_Doms;
	vector<string> m_SFs;
	vector<uint> m_SFIdxs;
	vector<uint> m_SFIdxToSize;
	map<string, uint> m_DomToIdx;
	map<string, uint> m_SFToIdx;
	float m_Open = -999;
	float m_Ext = -999;
	ALIGN_FN m_AF = 0;

//////////////////////////////
// Dope built from lookup+hits
// Defines subset of used doms
//////////////////////////////
	string m_DopeFN;
	uint m_DopeSize = 0;
	uint16_t *m_DomIdxQs = 0;	// idxs per lookup
	uint16_t *m_DomIdxTs = 0;	// idxs per lookop
	set<uint> m_DopeDomIdxs;	// unique used idxs
	bool *m_TPs = 0;
	uint m_NT = 0;
	vector<uint16_t> m_DomIdxQs_sorted;				// idxs per lookup
	vector<vector<uint16_t> > m_TargetDomIdxs;		// idxs per lookup
	vector<vector<uint16_t> > m_TargetPairIdxs;

////////////////////////////////
// Hits generated by this search
////////////////////////////////
	atomic<uint> m_NextQueryIdx = 0;
	float *m_Scores = 0;
	uint *m_ScoreOrder = 0;

//////////////////////////////
// Flat profiles
// May be superset of lookup
//////////////////////////////
	string m_specfn;
	vector<string> m_AlphaNames;
	vector<float> m_Weights;
	vector<uint> m_alpha_sizes;
	vector<string> m_profile_labels;
	vector<vector<uint8_t> > m_profiles;
	vector<uint16_t> m_DomIdx_to_profile_idx;	// DomIdxs per lookup
	uint m_MaxL = 0;

//////////////////////////////
// Log-odds matrices
//////////////////////////////
	vector<vector<float> > m_raw_logoddsmxvec;
	vector<vector<float> > m_weighted_logoddsmxvec;

//////////////////////////////
// Per-thread
//////////////////////////////
	uint m_ThreadCount = 0;

//////////////////////////////
// Bench
//////////////////////////////
	float m_Sum3 = 0;
	FastBench m_FB;

public:
	void validate_mappings() const;
	uint GetDomCount() const { return SIZE(m_Doms); }
	void ReadLookup(const string &FN);
	void AddDom(const string &Dom, const string &ScopId);
	void AllocDope(uint DopeSize);
	void AllocHits();
	void MakeDopeFromHits(const string &FN);
	uint16_t GetDomIdx(const string &Label, bool ErrOk) const;
	uint GetSFIdx(uint DomIdx) const;
	void WriteDope(const string &FN) const;
	void ReadDope(const string &FN);
	void ThreadBody(uint ThreadIdx);
	void Search();
	void ApplyWeightsToLogOdds(const unordered_map<string, float> &Weights);
	void Bench(const string &Msg = "");
	void SetScoreOrder();
	void WriteHits(const string &FN) const;
	void SetScalarParams(
		const vector<string> &Names,
		const vector<float> &Values);
	void UpdateParamsFromVarStr(const string &VarStr);
	void InitFB();
	void LoadAlphas(const string &SpecFN);
	void SortDope();
	void LoadStats() const;

public:
	static void ClassifyParams(
		const vector<string> &Names,
		const vector<float> &Values,
		vector<string> &AlphaNames,
		vector<float> &Weights,
		vector<string> &ScalarNames,
		vector<float> &ScalarValues);
	static void StaticThreadBody(flat_subsetbench *SB, uint ThreadIdx);
	};

void ParseVarStr(
	const string &VarStr,
	vector<string> &Names,
	vector<float> &Weights);

void TruncLabel(string &Label);
