#pragma once

#include "scop40bench.h"
#include "fastbench.h"
#include "flat_profiles.h"
#include "flat_aligner.h"
#include "flat_features.h"

class flat_bench : public FastBench
	{
public:
// Hard-coded score-like not Evalue-like
//	SBSCORE m_SBS = SBS_Evalue;

	uint m_ThreadCount = 0;

////////////////////////////////
// Hits generated by this search
////////////////////////////////
	atomic<uint> m_NextQueryIdx = 0;
	atomic<uint> m_NextDopeIdx = 0;

//////////////////////////////
// Flat profiles
// May be superset of lookup
//////////////////////////////
	flat_profiles m_fp;
	float *m_self_rev_scores = 0;

//////////////////////////////
// Distance matrices for
// structure features:
//	lddt, entropy, dali
//////////////////////////////
	vector<sid_t *> m_distmxs;

public:
	static atomic<uint> m_progress_counter;
	static atomic<uint> m_ncachehits;
	static atomic<uint> m_ncachemisses;

public:
	void Search(const string &how);
	void ApplyWeightsToLogOdds(const unordered_map<string, float> &Weights);
	void SetScalarParams(
		const vector<string> &Names,
		const vector<float> &Values);
	void UpdateParamsFromVarStr(const string &VarStr);
	void load_profiles(const string &fafnpattern, bool set_self_scores);
	void ProgressLogParams() const;
	void align_pair(const string &labelQ, const string &labelT);
	void align_pair_selfrev(FILE *f, uint DomIdx);
	void set_selfrev_scores();
	void set_distmxs(const string &chainfn);
	void doQ(flat_aligner &fa, uint domidxQ, uint domidxT);
	void doT(flat_aligner &fa, uint domidxT);


public:
// All-vs-all for fast SCOP40 benchmark score only
	virtual void ThreadBody_All(uint ThreadIdx);

// All-vs-all for fast SCOP40 benchmark score only
//	  with dope accelerator
	virtual void ThreadBody_Dope(uint ThreadIdx);

public:
	static void ClassifyParams(
		const vector<string> &Names,
		const vector<float> &Values,
		vector<string> &AlphaNames,
		vector<float> &Weights,
		vector<string> &ScalarNames,
		vector<float> &ScalarValues,
		float &selfw,
		float &revw,
		bool &need_distmxs);

	static void StaticThreadBody(flat_bench *SB,
		uint ThreadIdx, const string &how);;
	};

void ParseVarStr(
	const string &VarStr,
	vector<string> &Names,
	vector<float> &Weights);

void TruncLabel(string &Label);
