
const char *usage_txt[] =
    {
"Commands\n"
"  -search        # Alignment (e.g. DB search, pairwise, all-vs-all)\n"
"  -convert       # Convert file formats (e.g. create DB)\n"
"  -alignpair     # Pair-wise alignment and superposition\n"
"\n"
"Search against database\n"
"    reseek -search STRUCTS -db db.bcb -output hits.tsv\n"
"                 # use -convert to create .bcb files (below)\n"
"\n"
"Align and superpose two structures\n"
"    reseek -alignpair 1XYZ.pdb -input2 2ABC.pdb\n"
"           -aln FILE     # Sequence alignment (text)\n"
"           -output FILE  # Rotated 1XYZ (PDB format)\n"
"\n"
"Output options for -search\n"
"   -aln FILE     # Alignments in human-readable format\n"
"   -output FILE  # Hits in tabbed text format\n"
"   -columns name1+name2+name3...\n"
"                 # Output columns, names are\n"
"                 #   query   Query label\n"
"                 #   target  Target label\n"
"                 #   qlo     Start of aligment in query\n"
"                 #   qhi     End of aligment in query\n"
"                 #   tlo     Start of aligment in target\n"
"                 #   thi     End of aligment in target\n"
"                 #   ql      Query length\n"
"                 #   tl      Target length\n"
"                 #   pctid   Percent identity of alignment\n"
"                 #   cigar   CIGAR string\n"
"                 #   pvalue  p-value according to log-linear null model (recommended)\n"
"                 #   evalue  E-value assuming SCOP40 search (DEPRECATED)\n"
"                 #   qrow    Aligned query sequence with gaps (local)\n"
"                 #   trow    Aligned target sequence with gaps (local)\n"
"                 #   qrowg   Aligned query sequence with gaps (global)\n"
"                 #   trowg   Aligned target sequence with gaps (global)\n"
"                 #   qcovpct Query coverage (percent)\n"
"                 #   tcovpct Target coverage (percent)\n"
"                 #   std     query+target+qlo+qhi+ql+tlo+thi+tl+pctid+pvalue (default)\n"
"\n"
"Search and alignment options\n"
"  -fast or -sensitive  # Required\n"
"  -pvalue P            # Max P-value (default 0.001)\n"
"\n"
"Convert between file formats\n"
"    reseek -convert STRUCTS [one or more output options]\n"
"           -cal FILENAME    # .cal format, text with a.a. and C-alpha x,y,z\n"
"           -bca FILENAME    # .bca format, binary .cal\n"
"           -bcb FILENAME    # .bca format, binary .cal with nu, required for db\n"
"           -fasta FILENAME  # FASTA format\n"
"\n"
"STRUCTS argument is one of:\n"
"   NAME.cif or NAME.mmcif     # PDBx/mmCIF file\n"
"   NAME.pdb                   # Legacy format PDB file\n"
"   NAME.cal                   # C-alpha tabbed text format with chain(s)\n"
"   NAME.bcb                   # Binary C-alpha with nu, required for db\n"
"   NAME.bca                   # Binary C-alpha (used by earlier reseek versions)\n"
"   NAME.files                 # Text file with one STRUCT per line,\n"
"                              #   may be filename, directory or .files\n"
"   DIRECTORYNAME              # Directory (and its sub-directories) is searched\n"
"                              #   for known file types including .pdb, .files etc.\n"
"\n"
"Other options:\n"
"   -log FILENAME              # Log file with errors, warnings, time and memory.\n"
"   -threads N                 # Number of threads, default number of CPU cores.\n"
"\n"
"More documentation at https://drive5.com/reseek\n"
"\n"
    };
